package com.jetbrains.rider.plugins.specflowriderplugin.ideaInterop.fileTypes

import com.jetbrains.rider.ideaInterop.fileTypes.RiderDummySyntaxHighlighter

class GherkinSyntaxHighlighter : RiderDummySyntaxHighlighter(GherkinLanguage)