package com.jetbrains.rider.plugins.reqnrollriderplugin.psi.completion

import com.jetbrains.rider.completion.patchEngine.RiderPatchEngineCompletionContributor

class GherkinCompletionContributor : RiderPatchEngineCompletionContributor()