name: Update Issue Labels on Response

on:
  issue_comment:
    types: [created]

jobs:
  update-labels:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null # Only run on issues, not PRs
    permissions:
      issues: write
    steps:
      - name: User Responded Labels
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const comment = context.payload.comment;
            
            if (comment.user.type === 'Bot') {
              return;
            }
            
            const waitForResponseLabel = 'wait-for-user-response';
            const userRespondedLabel = 'user-responded';
            
            const hasWaitForResponseLabel = issue.labels.some(label => label.name === waitForResponseLabel);
            
            if (hasWaitForResponseLabel) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                name: waitForResponseLabel
              });
            
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: [userRespondedLabel]
              });
            
              console.log(`Replaced "${waitForResponseLabel}" with "${userRespondedLabel}" on issue #${issue.number}`);
            }